<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NeuroVisualizer.Core\Utils\PredictionHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="NeuroVisualizer.Core\Utils\PredictionHelper.cs" />
  </ItemGroup>

</Project>
